apiVersion: v1
kind: Service
metadata:
  name: seatsaver
  labels:
    app: seatsaver
spec:
  selector:
    app: seatsaver
  ports:
    -
      protocol: TCP
      port: 80
      targetPort: 4000
  type: NodePort